### ISSUE TITLE
Share a docker network

### ISSUE THREAD

**Issue by edavis** [edavis/fieldnotes#38]
There are probably more idiomatic ways to do this... but it works so jotting it down.

```
# ~/controlplane/docker-compose.yml
version: '3'
services:
  traefik:
    image: traefik:latest
    command: --api --docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik.toml
    networks:
      - traefik_net
  whoami:
    image: containous/whoami:latest
    labels:
      - "traefik.frontend.rule=Host:whoami.eresources.local"
    networks:
      - traefik_net
networks:
  traefik_net:
    driver: bridge
```

```
# ~/miniflux/docker-compose.yml
version: '3'
services:
  miniflux:
    image: miniflux/miniflux:latest
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://miniflux:secret@db/miniflux?sslmode=disable
      - RUN_MIGRATIONS=1
    networks:
      - controlplane_traefik_net
    labels:
      - "traefik.frontend.rule=Host:miniflux.eresources.local"
      - "traefik.port=8080"
  db:
    image: postgres:10.1
    environment:
      - POSTGRES_USER=miniflux
      - POSTGRES_PASSWORD=secret
    volumes:
      - miniflux-db:/var/lib/postgresql/data
    networks:
      - controlplane_traefik_net
volumes:
  miniflux-db:
networks:
  controlplane_traefik_net:
    external: true
```
